version: "3.8"

services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: agranelos-bff
    ports:
      - "80:8080"
    environment:
      - AZURE_FUNCTIONS_BASE_URL=https://agranelos-fybpb6duaadaaxfm.eastus2-01.azurewebsites.net/api
      - SPRING_SECURITY_USER_NAME=user
      - SPRING_SECURITY_USER_PASSWORD=myStrongPassword123

networks:
  default:
    name: agranelos-network
